#pragma once
#include "main.h"

void Event_usp(struct event_args_s *args);
void Event_ak47(struct event_args_s *args);
void Event_aug(struct event_args_s *args);
void Event_awp(struct event_args_s *args);
void Event_createexplo(struct event_args_s *args);
void Event_deagle(struct event_args_s *args);
void Event_elite_left(struct event_args_s *args);
void Event_elite_right(struct event_args_s *args);
void Event_famas(struct event_args_s *args);
void Event_fiveseven(struct event_args_s *args);
void Event_g3sg1(struct event_args_s *args);
void Event_galil(struct event_args_s *args);
void Event_glock(struct event_args_s *args);
void Event_m3(struct event_args_s *args);
void Event_m4a1(struct event_args_s *args);
void Event_m249(struct event_args_s *args);
void Event_mac10(struct event_args_s *args);
void Event_mp5n(struct event_args_s *args);
void Event_p90(struct event_args_s *args);
void Event_p228(struct event_args_s *args);
void Event_scout(struct event_args_s *args);
void Event_sg550(struct event_args_s *args);
void Event_sg552(struct event_args_s *args);
void Event_tmp(struct event_args_s *args);
void Event_ump45(struct event_args_s *args);
void Event_vehicle(struct event_args_s *args);
void Event_xm1014(struct event_args_s *args);
void Event_knife(struct event_args_s *args);
void Event_createsmoke(struct event_args_s *args);

extern pfnEventMsgHook pEvent_createsmoke;
extern pfnEventMsgHook pEvent_knife;
extern pfnEventMsgHook pEvent_usp;
extern pfnEventMsgHook pEvent_glock;
extern pfnEventMsgHook pEvent_ak47;
extern pfnEventMsgHook pEvent_aug;
extern pfnEventMsgHook pEvent_awp;
extern pfnEventMsgHook pEvent_createexplo;
extern pfnEventMsgHook pEvent_deagle;
extern pfnEventMsgHook pEvent_elite_left;
extern pfnEventMsgHook pEvent_elite_right;
extern pfnEventMsgHook pEvent_famas;
extern pfnEventMsgHook pEvent_fiveseven;
extern pfnEventMsgHook pEvent_g3sg1;
extern pfnEventMsgHook pEvent_galil;
extern pfnEventMsgHook pEvent_m3;
extern pfnEventMsgHook pEvent_m4a1;
extern pfnEventMsgHook pEvent_m249;
extern pfnEventMsgHook pEvent_mac10;
extern pfnEventMsgHook pEvent_mp5n;
extern pfnEventMsgHook pEvent_p90;
extern pfnEventMsgHook pEvent_p228;
extern pfnEventMsgHook pEvent_sg550;
extern pfnEventMsgHook pEvent_sg552;
extern pfnEventMsgHook pEvent_tmp;
extern pfnEventMsgHook pEvent_ump45;
extern pfnEventMsgHook pEvent_scout;
extern pfnEventMsgHook pEvent_vehicle;
extern pfnEventMsgHook pEvent_xm1014;